import AsyncStorage from '@react-native-async-storage/async-storage';
import React, {useEffect, useRef, useState} from 'react';
import {Alert, Animated, FlatList, Modal, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View} from 'react-native';
import Clipboard from '@react-native-clipboard/clipboard';
import {BackendAiService, type AiAnswer} from './src/services/AiService';
import {Message} from './src/components/Message';

type ChatMessage = {id: string; role: 'user'|'assistant'; text: string; answer?: AiAnswer};
const service = new BackendAiService();
const suggestions = ['Criar um sistema de inventário','Criar um sistema de sprint','Corrigir meu código','Explicar RemoteEvent'];

export default function App() {
  const [messages,setMessages] = useState<ChatMessage[]>([]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [drawer,setDrawer]=useState(false); const controller=useRef<AbortController>(); const list=useRef<FlatList<ChatMessage>>(null); const fade=useRef(new Animated.Value(0)).current;
  useEffect(()=>{ AsyncStorage.getItem('luvia-current-chat').then(saved=>saved&&setMessages(JSON.parse(saved))).catch(()=>undefined); Animated.timing(fade,{toValue:1,duration:350,useNativeDriver:true}).start();},[fade]);
  useEffect(()=>{ AsyncStorage.setItem('luvia-current-chat',JSON.stringify(messages)).catch(()=>undefined); list.current?.scrollToEnd({animated:true});},[messages]);
  const send=async(value=input)=>{const prompt=value.trim(); if(!prompt||loading)return; const user={id:`u-${Date.now()}`,role:'user' as const,text:prompt}; setMessages(current=>[...current,user]);setInput('');setLoading(true);controller.current=new AbortController();try {const answer=await service.answer(prompt,controller.current.signal);setMessages(current=>[...current,{id:`a-${Date.now()}`,role:'assistant',text:answer.reply,answer}]);}catch(error){setMessages(current=>[...current,{id:`e-${Date.now()}`,role:'assistant',text:(error as Error).message}]);}finally{setLoading(false);controller.current=undefined;}};
  const newChat=()=>{setMessages([]);setDrawer(false);};
  return <SafeAreaView style={styles.root}><Animated.View style={[styles.page,{opacity:fade}]}><View style={styles.header}><Pressable onPress={()=>setDrawer(true)}><Text style={styles.menu}>☰</Text></Pressable><View><Text style={styles.title}>Luvia</Text><Text style={styles.subtitle}>Assistente especializada em Luau e Roblox Studio.</Text></View></View>
    {messages.length===0?<View style={styles.empty}><Text style={styles.hero}>Crie melhor no Roblox.</Text><Text style={styles.hint}>Pergunte sobre Luau, sistemas, segurança ou performance.</Text><View style={styles.suggestions}>{suggestions.map(s=><Pressable key={s} style={styles.suggestion} onPress={()=>send(s)}><Text style={styles.suggestionText}>{s}</Text><Text style={styles.arrow}>↗</Text></Pressable>)}</View></View>:<FlatList ref={list} data={messages} keyExtractor={item=>item.id} renderItem={({item})=><Message role={item.role} text={item.text} codeBlocks={item.answer?.codeBlocks} onCopy={code=>{Clipboard.setString(code);Alert.alert('Código copiado');}}/>} contentContainerStyle={styles.list}/>}
    <View style={styles.composer}>{loading?<Pressable style={styles.stop} onPress={()=>controller.current?.abort()}><Text style={styles.stopText}>■ Parar geração</Text></Pressable>:<><TextInput value={input} onChangeText={setInput} placeholder="Pergunte à Luvia..." placeholderTextColor="#8790A8" multiline style={styles.input}/><Pressable style={[styles.send,!input.trim()&&styles.disabled]} onPress={()=>send()}><Text style={styles.sendText}>↑</Text></Pressable></>}</View>
  </Animated.View><Modal visible={drawer} transparent animationType="fade" onRequestClose={()=>setDrawer(false)}><Pressable style={styles.overlay} onPress={()=>setDrawer(false)}><Pressable style={styles.drawer} onPress={()=>undefined}><Text style={styles.drawerTitle}>Luvia</Text><Pressable style={styles.newChat} onPress={newChat}><Text style={styles.newChatText}>＋ Nova conversa</Text></Pressable><Text style={styles.drawerLabel}>CONVERSAS RECENTES</Text><Text style={styles.muted}>{messages.length?'Conversa atual':'Nenhuma conversa ainda'}</Text><View style={styles.spacer}/><Pressable onPress={()=>Alert.alert('Configurações','Aparência, Chat, Roblox e Sobre a Luvia estarão disponíveis aqui.')}><Text style={styles.settings}>⚙ Configurações</Text></Pressable></Pressable></Pressable></Modal></SafeAreaView>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#090B12'},page:{flex:1,paddingHorizontal:18},header:{paddingTop:18,flexDirection:'row',gap:16,alignItems:'center'},menu:{fontSize:25,color:'#C8D0F0'},title:{fontSize:24,fontWeight:'800',color:'#F4F5FA'},subtitle:{fontSize:13,color:'#A8B1C7',marginTop:2},empty:{flex:1,justifyContent:'center'},hero:{fontSize:30,fontWeight:'800',color:'#F1F3FA',letterSpacing:-.5},hint:{fontSize:16,color:'#A5AEC4',lineHeight:23,marginTop:10,marginBottom:28},suggestions:{gap:10},suggestion:{backgroundColor:'#131827',borderWidth:1,borderColor:'#222A40',borderRadius:14,padding:16,flexDirection:'row',justifyContent:'space-between'},suggestionText:{color:'#DCE2F5',fontSize:15},arrow:{color:'#9FACFF',fontSize:18},list:{paddingTop:24,paddingBottom:16},composer:{minHeight:64,marginBottom:12,backgroundColor:'#151A29',borderRadius:18,padding:8,flexDirection:'row',alignItems:'center'},input:{flex:1,maxHeight:112,color:'#F2F4FA',fontSize:16,paddingHorizontal:10,paddingVertical:8},send:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#7180F4'},disabled:{opacity:.45},sendText:{color:'#fff',fontSize:24,fontWeight:'700'},stop:{flex:1,alignItems:'center',padding:12},stopText:{color:'#FFB5BF',fontWeight:'700'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.56)'},drawer:{width:'82%',maxWidth:340,height:'100%',backgroundColor:'#101522',padding:24},drawerTitle:{fontSize:25,fontWeight:'800',color:'#F4F5FA',marginBottom:28},newChat:{padding:14,borderRadius:12,backgroundColor:'#6877E8'},newChatText:{color:'#fff',fontWeight:'800'},drawerLabel:{fontSize:10,fontWeight:'800',letterSpacing:1,color:'#7F89A2',marginTop:28,marginBottom:12},muted:{color:'#B6BED1'},spacer:{flex:1},settings:{fontSize:16,color:'#DDE3F6',paddingVertical:14}});
